// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvRo7bVm_-KJlvAOslg2xrbabsd-dhhkM',
    appId: '1:57599650844:web:7deb5abd125fc7f94e83d9',
    messagingSenderId: '57599650844',
    projectId: 'shelfsense-qwert',
    authDomain: 'shelfsense-qwert.firebaseapp.com',
    storageBucket: 'shelfsense-qwert.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZJWtQASgScwysxQFxP34VEE52bFXPwAg',
    appId: '1:57599650844:android:e7e8f05a4232fe794e83d9',
    messagingSenderId: '57599650844',
    projectId: 'shelfsense-qwert',
    storageBucket: 'shelfsense-qwert.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjr-sbe-nehz7GwGWOWjrQeegftGgC1-o',
    appId: '1:57599650844:ios:363663422c6f730c4e83d9',
    messagingSenderId: '57599650844',
    projectId: 'shelfsense-qwert',
    storageBucket: 'shelfsense-qwert.firebasestorage.app',
    iosBundleId: 'com.example.shelfSense',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjr-sbe-nehz7GwGWOWjrQeegftGgC1-o',
    appId: '1:57599650844:ios:363663422c6f730c4e83d9',
    messagingSenderId: '57599650844',
    projectId: 'shelfsense-qwert',
    storageBucket: 'shelfsense-qwert.firebasestorage.app',
    iosBundleId: 'com.example.shelfSense',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvRo7bVm_-KJlvAOslg2xrbabsd-dhhkM',
    appId: '1:57599650844:web:6c1329f2a4b001b84e83d9',
    messagingSenderId: '57599650844',
    projectId: 'shelfsense-qwert',
    authDomain: 'shelfsense-qwert.firebaseapp.com',
    storageBucket: 'shelfsense-qwert.firebasestorage.app',
  );
}
